// <auto-generated />
using System;
using LivrosAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LivrosAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220731195405_UsuarioCorrigidoCpf")]
    partial class UsuarioCorrigidoCpf
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LivrosAPI.Models.Livro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("autor");

                    b.Property<string>("Editora")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("editora");

                    b.Property<string>("Generos")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("generos");

                    b.Property<string>("Isbn10")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("isbn10");

                    b.Property<string>("Isbn13")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("isbn13");

                    b.Property<int>("QuantidadeDePaginas")
                        .HasColumnType("int")
                        .HasColumnName("quantidade_de_paginas");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("serie");

                    b.Property<string>("Subtitulo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("subtitulo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("titulo");

                    b.Property<int>("Volume")
                        .HasColumnType("int")
                        .HasColumnName("volume");

                    b.HasKey("Id");

                    b.ToTable("livro");
                });

            modelBuilder.Entity("LivrosAPI.Models.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cpf");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("matricula");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome_completo");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("senha");

                    b.Property<string>("Token")
                        .HasColumnType("longtext")
                        .HasColumnName("token");

                    b.Property<DateTime?>("ValidadeToken")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("validade_token");

                    b.HasKey("Id");

                    b.ToTable("usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
