// <auto-generated />
using LivrosAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LivrosAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220724150017_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LivrosAPI.Models.Livro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("autor");

                    b.Property<string>("Editora")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("editora");

                    b.Property<string>("Generos")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("generos");

                    b.Property<string>("Isbn10")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("isbn10");

                    b.Property<string>("Isbn13")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("isbn13");

                    b.Property<int>("QuantidadeDePaginas")
                        .HasColumnType("int")
                        .HasColumnName("quantidade_de_paginas");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("serie");

                    b.Property<string>("Subtitulo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("subtitulo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("titulo");

                    b.Property<int>("Volume")
                        .HasColumnType("int")
                        .HasColumnName("volume");

                    b.HasKey("Id");

                    b.ToTable("livro");
                });
#pragma warning restore 612, 618
        }
    }
}
